### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by iceshu** [lt-123/z390_aorus_pro_wifi-9700k-rx590#1]
我下了【黑果小兵】macOS Catalina 10.15.3 19D76 正式版 with Clover 5103原版镜像[双EFI版] 之后拷贝你的efi进去 之后就没有安装的按钮了
![image](https://user-images.githubusercontent.com/6309056/75113517-8b8cf300-5689-11ea-9056-308b688884e3.png)
我也是你这主板 然后配置一样 没有显卡还在路上免驱580

**Comment by paranoidharmony** [comment]
额，没遇到过这个问题。我最初安装时，也是用的小兵的镜像，并且安装时用的里面自带的EFI，这个EFI是我安装后，从其他地方得来的，我又自行更新下驱动以及修改了小部分配置，在我电脑上用着基本完美。

另外这个EFI我可能不继续维护了，因为我发现了这个板子的另一个EFI仓库，也推荐你用
https://github.com/shiruken/hackintosh

**Comment by iceshu** [comment]
ok我看下啊 多谢 第一次折腾黑苹果
